api_server:
  timeout: 1800
runners:
  timeout: 1500
  stage1_runner:
    resources:
      nvidia.com/gpu: [0]
  stage2_runner:
    resources:
      nvidia.com/gpu: [1]
  stage3_runner:
    resources:
      nvidia.com/gpu: [1]
